name: mariosocrates
favicon: null
layout_spectrum: 0.3889500121586025
typography_spectrum: 0.30667322082445025
title: Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#c3a384'
    - '#fdd1aa'
    - '#352614'
    - '#7b6441'
  brandStrength: 0.9102371919434518
  lightness: 0.7647742996923625
  saturation: 0.9052755709271878
  rhythmicContrast: 0.274749883916229
purpose: []
